In [2]:
import numpy as np

In [3]:
np.array([0,0,0,0,0,0,0,0,0,0])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.array([1,1,1,1,1,1,1,1,1,1])

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [15]:
a = np.random.randint(0,8,(3,3))
print(a)

[[7 5 3]
 [6 0 5]
 [5 3 7]]


In [20]:
def reverse_array(a):
    return np.flip(a)

a = np.array([1,2,3,4,5,6])
reverse_arr = reverse_array(a)
print(reverse_arr)

[6 5 4 3 2 1]


In [26]:
def extract_odd_array(a):
    return a[a % 2 == 1]

a = np.array([1,2,3,4,5,6,7,8,9])
odd_numbers = extract_odd_array(a)
print(odd_numbers)

[1 3 5 7 9]
