In [1]:
import numpy as np

In [2]:
np.array([2,3,4,5])

array([2, 3, 4, 5])

In [5]:
x = np.array([2,3,4,5])            # 1D array
x2d = np.array([[1,2,3],[4,5,6]])      # 2D array
x3d = np.array([[1,3],[4,2],[2,1],[3,4]])        # 3D array
print(x)
print(x2d)
print(x3d)

[2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[1 3]
 [4 2]
 [2 1]
 [3 4]]


In [7]:
# sequential matrix, np.arange() and np.linspace()
np.arange(0, 10, .2)          # 1D array answer

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [8]:
np.arange(0, 10, .2).size

50

In [9]:
np.arange(0, 10, .2).reshape(5, 10)

array([[0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8],
       [2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8],
       [4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8],
       [6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8],
       [8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8]])

In [25]:
np.linspace(0, 30, 15)

array([ 0.        ,  2.14285714,  4.28571429,  6.42857143,  8.57142857,
       10.71428571, 12.85714286, 15.        , 17.14285714, 19.28571429,
       21.42857143, 23.57142857, 25.71428571, 27.85714286, 30.        ])

In [26]:
np.linspace(0, 30, 15).size

15

In [29]:
np.linspace(0, 30, 15).reshape(5, 3)

array([[ 0.        ,  2.14285714,  4.28571429],
       [ 6.42857143,  8.57142857, 10.71428571],
       [12.85714286, 15.        , 17.14285714],
       [19.28571429, 21.42857143, 23.57142857],
       [25.71428571, 27.85714286, 30.        ]])

In [32]:
# randomized matrix with np.random
# np.random.rand()
print(np.random.rand(4,4))    # 0 to 1
print(np.random.rand(3,3))    # normal distribution
print(np.random.randint(-10,10,(3,3)))  # random int from -10 to 10
print(np.random.uniform(0,2,(3,3)))   # random float from 0 to 10
print(np.random.permutation([1,2,3,4,5,6,7,8,9,10]))  # random permutation

[[0.65918482 0.5129355  0.05354335 0.19444395]
 [0.20010029 0.47906491 0.01348995 0.03972673]
 [0.26811282 0.59051066 0.63524469 0.06748196]
 [0.62954851 0.19670911 0.53749117 0.54046655]]
[[0.04550144 0.39505237 0.32471385]
 [0.29854256 0.43524408 0.54982479]
 [0.90550807 0.32457233 0.48074968]]
[[ -4 -10   6]
 [  9   0 -10]
 [  7   4  -7]]
[[1.19822266 0.8863062  0.38708654]
 [1.53259271 1.94279828 0.52227268]
 [1.71093943 0.80483846 1.75747421]]
[ 2  6  4  9 10  8  7  5  3  1]


In [ ]:
xp = np.random.uniform

operations

In [33]:
a = np.random.randint(-10,10,(3,3))
b = np.random.randint(-10,10,(3,3))
print(a)
print(b)

[[ -1  -9  -9]
 [ -1   4   0]
 [ -3 -10   4]]
[[-10   4   9]
 [ -4  -7   8]
 [ -5  -4   9]]


In [34]:
# matrix and constant operations
a ** 2

array([[  1,  81,  81],
       [  1,  16,   0],
       [  9, 100,  16]])

In [35]:
# same size matrix operations
print(a + b)
print(a - b)
print(a / b)
print(a * b)         # element wise multiplication
print(a @ b)         # matrix multiplication

[[-11  -5   0]
 [ -5  -3   8]
 [ -8 -14  13]]
[[  9 -13 -18]
 [  3  11  -8]
 [  2  -6  -5]]
[[ 0.1        -2.25       -1.        ]
 [ 0.25       -0.57142857  0.        ]
 [ 0.6         2.5         0.44444444]]
[[ 10 -36 -81]
 [  4 -28   0]
 [ 15  40  36]]
[[  91   95 -162]
 [  -6  -32   23]
 [  50   42  -71]]


In [37]:
# mm
np.matmul(a,b)       

array([[  91,   95, -162],
       [  -6,  -32,   23],
       [  50,   42,  -71]])